package com.foxtv.app.core.iptv.channels

import androidx.compose.ui.graphics.Color

data class HardcodedChannel(
    val id: String,
    val name: String,
    val short: String,
    val category: String,
    val keywords: List<String>,
    val exclude: List<String> = emptyList(),
    val gradient: List<Color>,
    val iconUrl: String? = null,
    val backdropUrl: String? = null
)

object HardcodedChannels {
    fun matches(streamName: String, keywords: List<String>, exclude: List<String>? = null): Boolean {
        val lower = streamName.lowercase()
        if (!exclude.isNullOrEmpty()) {
            for (ex in exclude) {
                if (lower.contains(ex.lowercase())) return false
            }
        }
        for (kw in keywords) {
            val kwLower = kw.lowercase().trim()
            if (kwLower.isEmpty()) continue
            if (kwLower.length <= 3) {
                val regex = Regex("""(?:^|[^a-zA-Z0-9])""" + Regex.escape(kwLower) + """(?:$|[^a-zA-Z0-9])""")
                if (regex.containsMatchIn(lower)) return true
            } else {
                if (lower.contains(kwLower)) return true
            }
        }
        return false
    }

    fun byId(id: String): HardcodedChannel? = all.firstOrNull { it.id == id }

    fun byCategory(category: String): List<HardcodedChannel> =
        all.filter { it.category.equals(category, ignoreCase = true) }

    val all: List<HardcodedChannel> = listOf(
        HardcodedChannel(
            id = "ufc",
            name = "UFC Fight Pass",
            short = "UFC",
            category = "Combat",
            keywords = listOf("ufc", "fight pass", "mma", "ultimate fighting"),
            gradient = listOf(Color(0xFFD20A0A), Color(0xFF1A1A1A)),
            iconUrl = "https://upload.wikimedia.org/wikipedia/commons/thumb/9/99/UFC_Fight_Pass_Logo.svg/960px-UFC_Fight_Pass_Logo.svg.png",
            backdropUrl = "https://cdn.dribbble.com/userupload/44509326/file/1146907b6c2959c0a12c65d7259a58b6.png",
        ),
        HardcodedChannel(
            id = "wwe",
            name = "WWE Network",
            short = "WWE",
            category = "Combat",
            keywords = listOf("wwe", "raw", "smackdown", "nxt", "wrestlemania", "wrestling"),
            gradient = listOf(Color(0xFFCC0000), Color(0xFF000000)),
            iconUrl = "https://upload.wikimedia.org/wikipedia/commons/thumb/8/88/WWE_Network_logo.svg/500px-WWE_Network_logo.svg.png",
        ),
        HardcodedChannel(
            id = "aew",
            name = "All Elite Wrestling",
            short = "AEW",
            category = "Combat",
            keywords = listOf("aew", "dynamite", "rampage", "collision", "all elite"),
            gradient = listOf(Color(0xFFC59B27), Color(0xFF1E1E1E)),
            iconUrl = "https://i.imgur.com/5YO1phG.png",
        ),
        HardcodedChannel(
            id = "boxing",
            name = "World Boxing TV",
            short = "BOX",
            category = "Combat",
            keywords = listOf("boxing", "boxnation", "top rank", "matchroom", "pbc", "golden boy"),
            gradient = listOf(Color(0xFFB8860B), Color(0xFF2F4F4F)),
            iconUrl = "https://i.imgur.com/XCIBf7u.png",
        ),
        HardcodedChannel(
            id = "bellator",
            name = "Bellator MMA",
            short = "BEL",
            category = "Combat",
            keywords = listOf("bellator", "mma", "pfl", "mixed martial"),
            gradient = listOf(Color(0xFFE65100), Color(0xFF212121)),
            iconUrl = "https://i.imgur.com/VBKoLHk.png",
        ),
        HardcodedChannel(
            id = "ppv_events",
            name = "PPV Main Event",
            short = "PPV",
            category = "Combat",
            keywords = listOf("ppv", "pay per view", "box office", "ppv event", "ppv live", "main event ppv"),
            exclude = listOf("sky sports", "sky sport", "bt sport", "tnt sports"),
            gradient = listOf(Color(0xFF9C27B0), Color(0xFF1A237E)),
            iconUrl = "https://upload.wikimedia.org/wikipedia/en/e/e4/Main-event-au_logo.png",
        ),
        HardcodedChannel(
            id = "one_championship",
            name = "ONE Championship",
            short = "ONE",
            category = "Combat",
            keywords = listOf("one championship", "one fc", "muay thai", "kickboxing"),
            gradient = listOf(Color(0xFF00ACC1), Color(0xFF263238)),
            iconUrl = "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRVZj7DRrIAYrDkFvkf7jcILeUPKGvNiOOo8mfN6ZGXcw&s",
        ),
        HardcodedChannel(
            id = "f1",
            name = "Formula 1 TV",
            short = "F1",
            category = "Racing",
            keywords = listOf("f1", "formula 1", "formula one", "f1 tv", "grand prix", "sky f1", "fia"),
            gradient = listOf(Color(0xFFE10600), Color(0xFF15151E)),
            iconUrl = "https://upload.wikimedia.org/wikipedia/commons/thumb/e/eb/Sky_Sport_F1_-_Logo_2020.svg/960px-Sky_Sport_F1_-_Logo_2020.svg.png",
            backdropUrl = "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSSVqWT4V4T7Fup-rDDuJE80yKhdI4UJ8pvY7G-ACH-ihehjdkziDI03GA&s=10",
        ),
        HardcodedChannel(
            id = "motogp",
            name = "MotoGP",
            short = "MOTO",
            category = "Racing",
            keywords = listOf("motogp", "moto gp", "moto2", "moto3", "motorcycle racing"),
            gradient = listOf(Color(0xFF006699), Color(0xFF1C1C1C)),
            iconUrl = "https://i.pinimg.com/1200x/c1/bd/29/c1bd290b7e6438eae005500d785b8adf.jpg",
        ),
        HardcodedChannel(
            id = "nascar",
            name = "NASCAR Cup Series",
            short = "NASC",
            category = "Racing",
            keywords = listOf("nascar", "cup series", "xfinity", "daytona", "stock car"),
            gradient = listOf(Color(0xFFFFD700), Color(0xFF002B49)),
            iconUrl = "https://i.pinimg.com/1200x/5d/cd/3e/5dcd3e88c9179274b9bdae8e1ac95ded.jpg",
        ),
        HardcodedChannel(
            id = "indycar",
            name = "IndyCar Series",
            short = "INDY",
            category = "Racing",
            keywords = listOf("indycar", "indy 500", "indianapolis", "open wheel"),
            gradient = listOf(Color(0xFFD32F2F), Color(0xFF1A237E)),
            iconUrl = "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSyXDWlshhQc505zlQXzY4ZY1F9XbulITzIFDkx9TQaMA&s=10",
        ),
        HardcodedChannel(
            id = "wrc",
            name = "World Rally Championship (WRC)",
            short = "WRC",
            category = "Racing",
            keywords = listOf("wrc", "rally", "world rally", "fia rally"),
            gradient = listOf(Color(0xFFFF6D00), Color(0xFF37474F)),
            iconUrl = "https://upload.wikimedia.org/wikipedia/commons/9/9c/WRC.svg",
        ),
        HardcodedChannel(
            id = "superbike",
            name = "World Superbike (WSBK)",
            short = "WSBK",
            category = "Racing",
            keywords = listOf("wsbk", "world superbike", "superbike", "fim"),
            gradient = listOf(Color(0xFFC2185B), Color(0xFF212121)),
            iconUrl = "https://seeklogo.com/images/S/sbk-logo-2A94D6D61E-seeklogo.com.png",
        ),
        HardcodedChannel(
            id = "champions_league",
            name = "UEFA Champions League",
            short = "UCL",
            category = "Soccer",
            keywords = listOf("champions league", "ucl", "uefa", "europa league", "conference league"),
            gradient = listOf(Color(0xFF001489), Color(0xFF00083A)),
            iconUrl = "https://i.imgur.com/BzQphbw.png",
            backdropUrl = "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSKIVxbksY0xMHuE2bdQlwr_8QgHstejx_mlCCF-m3VIR5m3EAKXHdQbek&s=10",
        ),
        HardcodedChannel(
            id = "premier_league",
            name = "Premier League",
            short = "EPL",
            category = "Soccer",
            keywords = listOf("premier league", "epl", "english premier", "pl tv"),
            gradient = listOf(Color(0xFF38003C), Color(0xFF00FF87)),
            iconUrl = "https://upload.wikimedia.org/wikipedia/en/thumb/f/f2/Premier_League_Logo.svg/512px-Premier_League_Logo.svg.png",
        ),
        HardcodedChannel(
            id = "bein_sports",
            name = "beIN Sports HD",
            short = "beIN",
            category = "Soccer",
            keywords = listOf("bein", "bein sports", "bein 1", "bein 2", "bein 3", "bein 4", "bein sport"),
            gradient = listOf(Color(0xFF5C2D91), Color(0xFF1E1035)),
            iconUrl = "https://i.imgur.com/RLrMBlm.png",
            backdropUrl = "https://www.venclikovi.com/wp-content/uploads/2025/10/bein-sports-logo-global-streaming.webp",
        ),
        HardcodedChannel(
            id = "sky_sports",
            name = "Sky Sports Main Event",
            short = "SKY",
            category = "Soccer",
            keywords = listOf("sky sports", "sky sports football", "sky sports premier", "sky sports main", "sky sports news"),
            gradient = listOf(Color(0xFF001965), Color(0xFFE60000)),
            iconUrl = "https://cdn.skymedia.ie/wp-content/uploads/sites/4/2020/11/Sky-Sports-ME-2020-logo-250.png",
        ),
        HardcodedChannel(
            id = "tnt_sports",
            name = "TNT Sports HD",
            short = "TNT",
            category = "Soccer",
            keywords = listOf("tnt sports", "tnt sport", "bt sport", "tnt 1", "tnt 2", "tnt 3"),
            gradient = listOf(Color(0xFFE50000), Color(0xFF1A1A1A)),
            iconUrl = "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d3/TNT_Sports_2021_logo.svg/960px-TNT_Sports_2021_logo.svg.png",
        ),
        HardcodedChannel(
            id = "la_liga",
            name = "LaLiga TV HD",
            short = "LALIGA",
            category = "Soccer",
            keywords = listOf("laliga", "la liga", "laliga tv", "spanish league", "el clasico"),
            gradient = listOf(Color(0xFF101820), Color(0xFFFF4B44)),
            iconUrl = "https://i.imgur.com/ilay5Jr.png",
        ),
        HardcodedChannel(
            id = "serie_a",
            name = "Serie A TV",
            short = "SERIE",
            category = "Soccer",
            keywords = listOf("serie a", "calcio", "italian league", "serie a pass"),
            gradient = listOf(Color(0xFF003366), Color(0xFF0066CC)),
            iconUrl = "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e9/Serie_A_logo_2019.svg/512px-Serie_A_logo_2019.svg.png",
        ),
        HardcodedChannel(
            id = "bundesliga",
            name = "Bundesliga TV",
            short = "BUND",
            category = "Soccer",
            keywords = listOf("bundesliga", "german league", "bundesliga 1", "bundesliga 2"),
            gradient = listOf(Color(0xFFD3010C), Color(0xFF1A1A1A)),
            iconUrl = "https://upload.wikimedia.org/wikipedia/en/thumb/d/df/Bundesliga_logo_%282017%29.svg/512px-Bundesliga_logo_%282017%29.svg.png",
        ),
        HardcodedChannel(
            id = "ligue_1",
            name = "Ligue 1 Pass",
            short = "L1",
            category = "Soccer",
            keywords = listOf("ligue 1", "french league", "ligue 1 mcdonald", "ligue 1 uber"),
            gradient = listOf(Color(0xFF091C3E), Color(0xFF5EE8B7)),
            iconUrl = "https://i.imgur.com/PtzoOQL.png",
        ),
        HardcodedChannel(
            id = "mls",
            name = "MLS Season Pass",
            short = "MLS",
            category = "Soccer",
            keywords = listOf("mls", "major league soccer", "mls pass"),
            gradient = listOf(Color(0xFF002B49), Color(0xFFCC0000)),
            iconUrl = "https://i.imgur.com/S2pBerQ.png",
        ),
        HardcodedChannel(
            id = "world_cup",
            name = "FIFA World Cup",
            short = "FIFA",
            category = "Soccer",
            keywords = listOf("fifa", "world cup", "fifa plus", "fifa+"),
            gradient = listOf(Color(0xFF005696), Color(0xFF00A3E0)),
            iconUrl = "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9c/FIFA%2B_(2025).svg/960px-FIFA%2B_(2025).svg.png",
        ),
        HardcodedChannel(
            id = "copa_libertadores",
            name = "Copa Libertadores",
            short = "LIB",
            category = "Soccer",
            keywords = listOf("libertadores", "copa libertadores", "conmebol", "copa sudamericana"),
            gradient = listOf(Color(0xFFD4AF37), Color(0xFF1A1A1A)),
            iconUrl = "https://upload.wikimedia.org/wikipedia/commons/thumb/0/07/CONMEBOL_Libertadores_logo.svg/512px-CONMEBOL_Libertadores_logo.svg.png",
        ),
        HardcodedChannel(
            id = "beout_q",
            name = "SuperSport HD",
            short = "SUPER",
            category = "Soccer",
            keywords = listOf("supersport", "super sport", "dstv", "supersport premier", "supersport football"),
            gradient = listOf(Color(0xFF005BA6), Color(0xFFD31145)),
            iconUrl = "https://i.imgur.com/KXdVDis.png",
        ),
        HardcodedChannel(
            id = "espn",
            name = "ESPN HD",
            short = "ESPN",
            category = "Sports",
            keywords = listOf("espn hd", "espn 1", "espn live", "espn usa", "espn us", "espn main", "espn east", "espn west", "espn 1080"),
            exclude = listOf("espn2", "espn 2", "espnu", "espn u", "espn+", "espn plus", "espn news", "espnews", "espn deportes", "sec", "acc"),
            gradient = listOf(Color(0xFFCC0000), Color(0xFF1A1A1A)),
            iconUrl = "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2f/ESPN_wordmark.svg/960px-ESPN_wordmark.svg.png",
            backdropUrl = "https://disney.images.edge.bamgrid.com/ripcut-delivery/v2/variant/espn/0EED69F98BADBE7F760C4F96CED05B20C7992B56AF98DD17A1E9BD18F128FD8E/compose?format=webp&width=2560",
        ),
        HardcodedChannel(
            id = "espn_plus",
            name = "ESPN+ Live Events & Exclusives",
            short = "ESPN+",
            category = "Sports",
            keywords = listOf("espn+", "espn plus", "espnplus", "espn +", "espn-plus", "espn+ 1", "espn+ 2", "espn+ 3", "espn+ 4", "espn+ 5", "espn+ 6", "espn+ 7", "espn+ 8", "espn+ 9", "espn+ 10", "espn+ event", "espn+ live", "espn plus 1", "espn plus 2", "espn plus 3", "espn plus 4", "espn plus 5", "espn+ stream"),
            gradient = listOf(Color(0xFF003087), Color(0xFFCC0000)),
            iconUrl = "https://upload.wikimedia.org/wikipedia/commons/thumb/7/77/ESPN%2B_logo.svg/512px-ESPN%2B_logo.svg.png",
            backdropUrl = "https://cdn.dribbble.com/userupload/44509326/file/1146907b6c2959c0a12c65d7259a58b6.png",
        ),
        HardcodedChannel(
            id = "espn2",
            name = "ESPN2 HD",
            short = "ESPN2",
            category = "Sports",
            keywords = listOf("espn 2", "espn2", "espn 2 hd", "espn2 hd", "espn 2 usa", "espn 2 live"),
            gradient = listOf(Color(0xFFCC0000), Color(0xFF003087)),
            iconUrl = "https://upload.wikimedia.org/wikipedia/commons/thumb/9/91/ESPN2_wordmark.svg/512px-ESPN2_wordmark.svg.png",
        ),
        HardcodedChannel(
            id = "espnu",
            name = "ESPNU (College Sports)",
            short = "ESPNU",
            category = "Sports",
            keywords = listOf("espnu", "espn u", "espnu hd", "espn u hd", "espn university", "espn college"),
            gradient = listOf(Color(0xFFCC0000), Color(0xFF000000)),
            iconUrl = "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d7/ESPNU_logo.svg/512px-ESPNU_logo.svg.png",
        ),
        HardcodedChannel(
            id = "espnews",
            name = "ESPNews HD",
            short = "NEWS",
            category = "Sports",
            keywords = listOf("espnews", "espn news", "espnews hd", "espn news hd"),
            gradient = listOf(Color(0xFF8B0000), Color(0xFF1C1C1C)),
            iconUrl = "https://upload.wikimedia.org/wikipedia/commons/thumb/6/67/ESPNews_logo.svg/512px-ESPNews_logo.svg.png",
        ),
        HardcodedChannel(
            id = "espn_deportes",
            name = "ESPN Deportes",
            short = "DEP",
            category = "Sports",
            keywords = listOf("espn deportes", "espndeportes", "espn deportes hd"),
            gradient = listOf(Color(0xFFCC0000), Color(0xFFD4AF37)),
            iconUrl = "https://upload.wikimedia.org/wikipedia/commons/thumb/c/cf/ESPN_Deportes_logo.svg/512px-ESPN_Deportes_logo.svg.png",
        ),
        HardcodedChannel(
            id = "sec_network",
            name = "SEC Network & SEC+",
            short = "SEC",
            category = "Sports",
            keywords = listOf("sec network", "secn", "sec network+", "sec network +", "sec network plus", "sec alt", "sec alternate", "sec hd"),
            gradient = listOf(Color(0xFF002D62), Color(0xFFFFD100)),
            iconUrl = "https://upload.wikimedia.org/wikipedia/commons/thumb/9/90/SEC_Network_logo.svg/512px-SEC_Network_logo.svg.png",
        ),
        HardcodedChannel(
            id = "acc_network",
            name = "ACC Network & ACCNX",
            short = "ACC",
            category = "Sports",
            keywords = listOf("acc network", "accn", "acc network+", "acc network +", "acc network plus", "acc extra", "accx", "acc hd"),
            gradient = listOf(Color(0xFF013CA6), Color(0xFF9FA1A4)),
            iconUrl = "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e6/ACC_Network_logo.svg/512px-ACC_Network_logo.svg.png",
        ),
        HardcodedChannel(
            id = "longhorn_network",
            name = "Longhorn Network (LHN)",
            short = "LHN",
            category = "Sports",
            keywords = listOf("longhorn network", "longhorn", "lhn", "texas longhorns"),
            gradient = listOf(Color(0xFFBF5700), Color(0xFF333F48)),
            iconUrl = "https://upload.wikimedia.org/wikipedia/commons/thumb/9/99/Longhorn_Network_logo.svg/512px-Longhorn_Network_logo.svg.png",
        ),
        HardcodedChannel(
            id = "ncaa_cbb",
            name = "NCAA College Basketball (CBB Hub)",
            short = "CBB",
            category = "Sports",
            keywords = listOf("ncaa basketball", "college basketball", "ncaab", "ncaaw", "march madness", "ncaa tournament", "cbb live", "ncaa cbb", "mens basketball", "womens basketball", "mens basketball", "womens basketball", "ncaa hoops", "college hoops"),
            gradient = listOf(Color(0xFF005696), Color(0xFFFF6600)),
            iconUrl = "https://upload.wikimedia.org/wikipedia/commons/thumb/d/dd/NCAA_logo.svg/512px-NCAA_logo.svg.png",
            backdropUrl = "https://cdn.dribbble.com/userupload/44509326/file/1146907b6c2959c0a12c65d7259a58b6.png",
        ),
        HardcodedChannel(
            id = "big_ten_network",
            name = "Big Ten Network (BTN & BTN+)",
            short = "BTN",
            category = "Sports",
            keywords = listOf("big ten network", "btn", "big 10 network", "big ten", "btn+", "btn plus", "big 10", "btn hd"),
            gradient = listOf(Color(0xFF003087), Color(0xFF000000)),
            iconUrl = "https://upload.wikimedia.org/wikipedia/commons/thumb/5/52/Big_Ten_Network_2020_Logo.svg/512px-Big_Ten_Network_2020_Logo.svg.png",
        ),
        HardcodedChannel(
            id = "pac_12_network",
            name = "Pac-12 Network",
            short = "PAC12",
            category = "Sports",
            keywords = listOf("pac-12", "pac 12", "pac-12 network", "pac 12 network", "pac-12 bay area", "pac-12 los angeles", "pac-12 mountain", "pac-12 oregon", "pac-12 washington", "pac-12 arizona", "pac 12 national"),
            gradient = listOf(Color(0xFF004B87), Color(0xFF002244)),
            iconUrl = "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e0/Pac-12_Network_Logo.svg/512px-Pac-12_Network_Logo.svg.png",
        ),
        HardcodedChannel(
            id = "bally_sports",
            name = "FanDuel / Bally Sports HD",
            short = "FDSN",
            category = "Sports",
            keywords = listOf("fanduel sports", "bally sports", "bally sports south", "bally sports midwest", "bally sports sun", "bally sports florida", "bally sports detroit", "bally sports ohio", "bally sports west", "bally sports socal", "bally sports north", "bally sports wisconsin", "bally sports southwest", "bally sports southeast", "bally sports indiana"),
            gradient = listOf(Color(0xFF0D1B2A), Color(0xFF1B4965)),
            iconUrl = "https://upload.wikimedia.org/wikipedia/commons/thumb/8/87/FanDuel_Sports_Network_logo.svg/512px-FanDuel_Sports_Network_logo.svg.png",
        ),
        HardcodedChannel(
            id = "fox_sports",
            name = "FOX Sports 1 (FS1)",
            short = "FOX",
            category = "Sports",
            keywords = listOf("fox sports", "fs1", "fs2", "fox sports 1", "fox sports 2", "fox soccer"),
            gradient = listOf(Color(0xFF003366), Color(0xFF0066CC)),
            iconUrl = "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3b/FOX_Deportes_logo.png/960px-FOX_Deportes_logo.png",
        ),
        HardcodedChannel(
            id = "nbc_sports",
            name = "NBC Sports",
            short = "NBC",
            category = "Sports",
            keywords = listOf("nbc sports", "nbcsn", "peacock sports", "nbc golf"),
            gradient = listOf(Color(0xFF0078D7), Color(0xFF2C3E50)),
            iconUrl = "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9e/NBCSN_logo_%28flat%29.svg/960px-NBCSN_logo_%28flat%29.svg.png",
        ),
        HardcodedChannel(
            id = "cbs_sports",
            name = "CBS Sports Network",
            short = "CBS",
            category = "Sports",
            keywords = listOf("cbs sports", "cbssn", "cbs sports network", "paramount sports"),
            gradient = listOf(Color(0xFF002244), Color(0xFF005596)),
            iconUrl = "https://i.imgur.com/q8BENJg.png",
        ),
        HardcodedChannel(
            id = "nba",
            name = "NBA TV HD",
            short = "NBA",
            category = "Sports",
            keywords = listOf("nba tv", "nba league pass", "nba hd", "basketball"),
            gradient = listOf(Color(0xFF17408B), Color(0xFFC9082A)),
            iconUrl = "https://i.imgur.com/Bwv5KgE.png",
            backdropUrl = "https://m.media-amazon.com/images/S/sonata-images-prod/US_CHANNELS_NBATV_SeasonKickoff_1019/497224e7-8ed5-4063-b9c4-33ec7a46fa20._UR1920,1080_.jpeg",
        ),
        HardcodedChannel(
            id = "nfl",
            name = "NFL Network",
            short = "NFL",
            category = "Sports",
            keywords = listOf("nfl network", "nfl game pass", "nfl sunday ticket", "nfl hd", "american football"),
            gradient = listOf(Color(0xFF013369), Color(0xFFD50A0A)),
            iconUrl = "https://upload.wikimedia.org/wikipedia/en/thumb/8/8f/NFL_Network_logo.svg/960px-NFL_Network_logo.svg.png",
        ),
        HardcodedChannel(
            id = "nfl_redzone",
            name = "NFL RedZone",
            short = "RED",
            category = "Sports",
            keywords = listOf("nfl redzone", "redzone", "red zone", "nfl red zone"),
            gradient = listOf(Color(0xFFD50A0A), Color(0xFF013369)),
            iconUrl = "https://i.imgur.com/5lPqQj5.png",
        ),
        HardcodedChannel(
            id = "nhl",
            name = "NHL Network",
            short = "NHL",
            category = "Sports",
            keywords = listOf("nhl network", "nhl center ice", "nhl hd", "ice hockey", "stanley cup"),
            gradient = listOf(Color(0xFF000000), Color(0xFF003366)),
            iconUrl = "https://i.imgur.com/UNZ8bef.png",
        ),
        HardcodedChannel(
            id = "mlb",
            name = "MLB Network",
            short = "MLB",
            category = "Sports",
            keywords = listOf("mlb network", "mlb extra innings", "mlb hd", "baseball", "world series"),
            gradient = listOf(Color(0xFF002D62), Color(0xFFBA0C2F)),
            iconUrl = "https://i.imgur.com/ym3su2J.png",
        ),
        HardcodedChannel(
            id = "dazn",
            name = "DAZN 1 HD",
            short = "DAZN",
            category = "Sports",
            keywords = listOf("dazn", "dazn 1", "dazn 2", "dazn combat", "dazn boxing"),
            gradient = listOf(Color(0xFFF8F8F8), Color(0xFF1E1E1E)),
            iconUrl = "https://upload.wikimedia.org/wikipedia/commons/thumb/4/49/DAZN_1.svg/500px-DAZN_1.svg.png",
        ),
        HardcodedChannel(
            id = "eurosport",
            name = "Eurosport 1 HD",
            short = "EURO",
            category = "Sports",
            keywords = listOf("eurosport", "eurosport 1", "eurosport 2", "discovery sports"),
            gradient = listOf(Color(0xFF002B49), Color(0xFF005696)),
            iconUrl = "https://i.imgur.com/s4jDnJh.png",
        ),
        HardcodedChannel(
            id = "hbo",
            name = "HBO HD",
            short = "HBO",
            category = "Movies",
            keywords = listOf("hbo", "hbo 2", "hbo signature", "hbo comedy", "hbo zone", "hbo family", "hbo max"),
            gradient = listOf(Color(0xFF5C2D91), Color(0xFF1A1A1A)),
            iconUrl = "https://upload.wikimedia.org/wikipedia/commons/thumb/d/de/HBO_logo.svg/960px-HBO_logo.svg.png",
            backdropUrl = "https://wallpapercat.com/w/full/8/2/d/1263212-1920x1080-desktop-1080p-hbo-background-image.jpg",
        ),
        HardcodedChannel(
            id = "showtime",
            name = "Showtime HD",
            short = "SHO",
            category = "Movies",
            keywords = listOf("showtime", "sho 2", "sho showcase", "sho extreme", "paramount with showtime"),
            gradient = listOf(Color(0xFFCC0000), Color(0xFF1A1A1A)),
            iconUrl = "https://i.imgur.com/Or0LKsu.png",
        ),
        HardcodedChannel(
            id = "starz",
            name = "Starz HD",
            short = "STARZ",
            category = "Movies",
            keywords = listOf("starz", "starz edge", "starz inblack", "starz cinema", "starz comedy"),
            gradient = listOf(Color(0xFF000000), Color(0xFF2C3E50)),
            iconUrl = "https://i.imgur.com/N7oSm4d.png",
        ),
        HardcodedChannel(
            id = "cinemax",
            name = "Cinemax HD",
            short = "MAX",
            category = "Movies",
            keywords = listOf("cinemax", "moremax", "actionmax", "thrillermax", "outermax"),
            gradient = listOf(Color(0xFFFFD700), Color(0xFF1A1A1A)),
            iconUrl = "https://i.imgur.com/cZWoJWD.png",
        ),
        HardcodedChannel(
            id = "paramount",
            name = "Paramount Network",
            short = "PARA",
            category = "Movies",
            keywords = listOf("paramount", "paramount network", "paramount channel"),
            gradient = listOf(Color(0xFF006699), Color(0xFF1A1A1A)),
            iconUrl = "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9f/Paramount_Network.svg/960px-Paramount_Network.svg.png",
        ),
        HardcodedChannel(
            id = "amc",
            name = "AMC HD",
            short = "AMC",
            category = "Movies",
            keywords = listOf("amc", "amc plus", "amc+", "american movie classics"),
            gradient = listOf(Color(0xFF8B0000), Color(0xFF1A1A1A)),
            iconUrl = "https://i.imgur.com/yj8RNnG.png",
        ),
        HardcodedChannel(
            id = "fx",
            name = "FX HD",
            short = "FX",
            category = "Movies",
            keywords = listOf("fx", "fxx", "fxm", "fx movie channel"),
            gradient = listOf(Color(0xFF212121), Color(0xFF424242)),
            iconUrl = "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR93lsxzG6S5N-824mfcmR1dwUz1RE0lnf0ebmOE70DcQ&s",
        ),
        HardcodedChannel(
            id = "sky_cinema",
            name = "Sky Cinema Premiere",
            short = "SKY C",
            category = "Movies",
            keywords = listOf("sky cinema", "sky movies", "sky premiere", "sky action", "sky comedy", "sky scifi"),
            gradient = listOf(Color(0xFF800020), Color(0xFF1A1A1A)),
            iconUrl = "https://upload.wikimedia.org/wikipedia/en/thumb/1/18/Sky_Cinema_Premiere_2024_logo.svg/960px-Sky_Cinema_Premiere_2024_logo.svg.png",
        ),
        HardcodedChannel(
            id = "osn_movies",
            name = "OSN Movies Premiere",
            short = "OSN M",
            category = "Movies",
            keywords = listOf("osn movies", "osn premiere", "osn action", "osn comedy", "osn cinema"),
            gradient = listOf(Color(0xFF9C27B0), Color(0xFF1A1A1A)),
            iconUrl = "https://media0106.elcinema.com/tvguide/1213_1.png",
        ),
        HardcodedChannel(
            id = "cnn",
            name = "CNN International",
            short = "CNN",
            category = "News",
            keywords = listOf("cnn", "cnn international", "cnn news", "cnn hd"),
            gradient = listOf(Color(0xFFCC0000), Color(0xFF1A1A1A)),
            iconUrl = "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b1/CNN.svg/960px-CNN.svg.png",
        ),
        HardcodedChannel(
            id = "bbc_news",
            name = "BBC World News",
            short = "BBC",
            category = "News",
            keywords = listOf("bbc news", "bbc world news", "bbc world", "bbc hd"),
            gradient = listOf(Color(0xFFBB1919), Color(0xFF1A1A1A)),
            iconUrl = "https://ltsk-cdn.s3.eu-west-1.amazonaws.com/jumpstart/Temp_Live/cdn/HLS/Channel/transparentImages/BBC-logo_2000_X_1125_Transparent.png",
        ),
        HardcodedChannel(
            id = "fox_news",
            name = "Fox News Channel",
            short = "FNC",
            category = "News",
            keywords = listOf("fox news", "fox business", "fnc", "fox news hd"),
            gradient = listOf(Color(0xFF003366), Color(0xFFCC0000)),
            iconUrl = "https://upload.wikimedia.org/wikipedia/commons/thumb/6/67/Fox_News_Channel_logo.svg/960px-Fox_News_Channel_logo.svg.png",
        ),
        HardcodedChannel(
            id = "msnbc",
            name = "MSNBC News",
            short = "MSNBC",
            category = "News",
            keywords = listOf("msnbc", "msnbc news", "msnbc hd"),
            gradient = listOf(Color(0xFF005696), Color(0xFF1A1A1A)),
            iconUrl = "https://upload.wikimedia.org/wikipedia/commons/7/7f/MSNBC_2023.svg",
        ),
        HardcodedChannel(
            id = "sky_news",
            name = "Sky News HD",
            short = "SKY N",
            category = "News",
            keywords = listOf("sky news", "sky news uk", "sky news arabia", "sky news international"),
            gradient = listOf(Color(0xFFCC0000), Color(0xFF001965)),
            iconUrl = "https://d2n0069hmnqmmx.cloudfront.net/epgdata/1.0/newchanlogos/512/512/skychb1404.png",
        ),
        HardcodedChannel(
            id = "al_jazeera",
            name = "Al Jazeera English",
            short = "AJE",
            category = "News",
            keywords = listOf("al jazeera", "al jazeera english", "al jazeera news", "aljazeera"),
            gradient = listOf(Color(0xFFD4AF37), Color(0xFF1A1A1A)),
            iconUrl = "https://dtil.tmsimg.com/assets/s159135_ld_h15_aa.png?lock=720x540",
        ),
        HardcodedChannel(
            id = "cnbc",
            name = "CNBC HD",
            short = "CNBC",
            category = "News",
            keywords = listOf("cnbc", "cnbc news", "cnbc international", "cnbc us"),
            gradient = listOf(Color(0xFF002B49), Color(0xFF005696)),
            iconUrl = "https://upload.wikimedia.org/wikipedia/commons/thumb/b/bc/CNBC_2025.svg/960px-CNBC_2025.svg.png",
        ),
        HardcodedChannel(
            id = "bloomberg",
            name = "Bloomberg TV",
            short = "BLOOM",
            category = "News",
            keywords = listOf("bloomberg", "bloomberg tv", "bloomberg news", "bloomberg financial"),
            gradient = listOf(Color(0xFF000000), Color(0xFF333333)),
            iconUrl = "https://i.imgur.com/R7FCaB5.png",
        ),
        HardcodedChannel(
            id = "france24",
            name = "France 24 English",
            short = "F24",
            category = "News",
            keywords = listOf("france 24", "france 24 english", "france 24 news"),
            gradient = listOf(Color(0xFF002B49), Color(0xFF005696)),
            iconUrl = "https://ltsk-cdn.s3.eu-west-1.amazonaws.com/jumpstart/Temp_Live/cdn/HLS/Channel/transparentImages/France%2024.png",
        ),
        HardcodedChannel(
            id = "mbc",
            name = "MBC 1 HD",
            short = "MBC1",
            category = "Arabic",
            keywords = listOf("mbc", "mbc 1", "mbc masr", "mbc drama", "mbc action", "mbc 2", "mbc 4"),
            gradient = listOf(Color(0xFF8E24AA), Color(0xFF1A1A1A)),
            iconUrl = "https://i.imgur.com/CiA3plN.png",
        ),
        HardcodedChannel(
            id = "rotana",
            name = "Rotana Cinema HD",
            short = "ROT",
            category = "Arabic",
            keywords = listOf("rotana", "rotana cinema", "rotana classic", "rotana drama", "rotana khaleejiya"),
            gradient = listOf(Color(0xFFE65100), Color(0xFF1A1A1A)),
            iconUrl = "https://i.imgur.com/2zFQbQi.png",
        ),
        HardcodedChannel(
            id = "osn",
            name = "OSN TV HD",
            short = "OSN",
            category = "Arabic",
            keywords = listOf("osn", "osn ya hala", "osn series", "osn news", "osn pop up"),
            gradient = listOf(Color(0xFFD500F9), Color(0xFF1A1A1A)),
            iconUrl = "https://www.osn.com/osn/media/OSNMedia/osntv/images/common/osntv-purple-logo-hub.png",
        ),
        HardcodedChannel(
            id = "abu_dhabi",
            name = "Abu Dhabi Sports HD",
            short = "AD SP",
            category = "Arabic",
            keywords = listOf("abu dhabi", "abu dhabi sports", "ad sports", "ad sports 1", "ad sports 2"),
            gradient = listOf(Color(0xFF00897B), Color(0xFF1A1A1A)),
            iconUrl = "https://i.imgur.com/8DAriPs.png",
        ),
        HardcodedChannel(
            id = "dubai_tv",
            name = "Dubai Sports HD",
            short = "DXB SP",
            category = "Arabic",
            keywords = listOf("dubai sports", "dubai tv", "dubai one", "dubai sports 1", "dubai sports 2"),
            gradient = listOf(Color(0xFF039BE5), Color(0xFF1A1A1A)),
            iconUrl = "https://i.imgur.com/Dj16oKL.png",
        ),
        HardcodedChannel(
            id = "alarabiya",
            name = "Al Arabiya News",
            short = "ARAB",
            category = "Arabic",
            keywords = listOf("al arabiya", "alarabiya", "alhadath", "al hadath", "arabiya news"),
            gradient = listOf(Color(0xFF5E35B1), Color(0xFF1A1A1A)),
            iconUrl = "https://shahid.mbc.net/mediaObject/a4c125db-ede8-4970-9eed-963948c78651?height=auto&width=512&croppingPoint=&version=1&type=png",
        ),
        HardcodedChannel(
            id = "discovery",
            name = "Discovery Channel HD",
            short = "DISC",
            category = "Discovery",
            keywords = listOf("discovery", "discovery channel", "discovery science", "discovery turbo"),
            gradient = listOf(Color(0xFF006699), Color(0xFF1A1A1A)),
            iconUrl = "https://upload.wikimedia.org/wikipedia/tr/6/69/Discovery_HD_logo.PNG",
        ),
        HardcodedChannel(
            id = "nat_geo",
            name = "National Geographic HD",
            short = "NATGEO",
            category = "Discovery",
            keywords = listOf("national geographic", "nat geo", "nat geo wild", "nat geo people"),
            gradient = listOf(Color(0xFFFFD700), Color(0xFF1A1A1A)),
            iconUrl = "https://upload.wikimedia.org/wikipedia/commons/thumb/f/fc/Natgeologo.svg/960px-Natgeologo.svg.png",
        ),
        HardcodedChannel(
            id = "history",
            name = "History Channel HD",
            short = "HIST",
            category = "Discovery",
            keywords = listOf("history", "history channel", "history 2", "h2"),
            gradient = listOf(Color(0xFFC59B27), Color(0xFF1A1A1A)),
            iconUrl = "https://banner2.cleanpng.com/20180724/rzb/5ccd9cc4a44cbe8a363610a7d240aba9.webp",
        ),
        HardcodedChannel(
            id = "animal_planet",
            name = "Animal Planet HD",
            short = "ANIMAL",
            category = "Discovery",
            keywords = listOf("animal planet", "animal planet hd"),
            gradient = listOf(Color(0xFF43A047), Color(0xFF1A1A1A)),
            iconUrl = "https://upload.wikimedia.org/wikipedia/commons/thumb/2/20/2018_Animal_Planet_logo.svg/960px-2018_Animal_Planet_logo.svg.png",
        ),
        HardcodedChannel(
            id = "cartoon_network",
            name = "Cartoon Network HD",
            short = "CN",
            category = "Kids",
            keywords = listOf("cartoon network", "cn", "boomerang"),
            gradient = listOf(Color(0xFF000000), Color(0xFF00AEEF)),
            iconUrl = "https://upload.wikimedia.org/wikipedia/commons/thumb/8/80/Cartoon_Network_2010_logo.svg/960px-Cartoon_Network_2010_logo.svg.png",
        ),
        HardcodedChannel(
            id = "disney",
            name = "Disney Channel HD",
            short = "DISNEY",
            category = "Kids",
            keywords = listOf("disney", "disney channel", "disney xd", "disney junior"),
            gradient = listOf(Color(0xFF005696), Color(0xFF00A3E0)),
            iconUrl = "https://upload.wikimedia.org/wikipedia/commons/b/bb/Disney_Channel_2014_HD.png",
        ),
        HardcodedChannel(
            id = "nickelodeon",
            name = "Nickelodeon HD",
            short = "NICK",
            category = "Kids",
            keywords = listOf("nickelodeon", "nick", "nick jr", "nicktoons"),
            gradient = listOf(Color(0xFFFF6D00), Color(0xFF1A1A1A)),
            iconUrl = "https://i.imgur.com/E84jnP8.png",
        ),
        HardcodedChannel(
            id = "spacetoon",
            name = "Spacetoon HD",
            short = "SPACE",
            category = "Kids",
            keywords = listOf("spacetoon", "space toon", "spacetoon go"),
            gradient = listOf(Color(0xFF00ACC1), Color(0xFF1A1A1A)),
            iconUrl = "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSNLD0wanJTx5fZ0NXpXfh3nTKwsi96CG_tRDiuJn_AyD3JCCdsLadCSMY&s=10",
        )
    )
}
